language: php

php:
    - '7.3'

before_install:
    # configure timezone: https://stackoverflow.com/a/27052708/1348344
    - export TZ=Europe/Prague

install:
    - composer install

jobs:
    include:
        -
            stage: test
            name: PHPUnit
            script:
                - vendor/bin/phpunit

        -
            name: ECS
            script:
                - composer check-cs

        -
            name: PHSPtan
            script:
                - composer phpstan

        -
            name: check Duplicated Groups
            script:
                - bin/console validate-groups

        -
            stage: deploy
            name: 'Deploy to Github Pages'
            if: branch = master AND type = push
            script:
                # import data
                - bin/console import -vvv
                # generate website to "/output" directory
                - vendor/bin/statie generate source -vvv

            # see docs: https://www.statie.org/docs/github-pages/
            deploy:
                provider: pages
                skip_cleanup: true
                github_token: $GITHUB_TOKEN
                local_dir: output

matrix:
    fast_finish: true

notifications:
    email:
        on_success: never
