imports:
    - { resource: 'services.yaml' }

parameters:
    meetup_com_oauth_key: '%env(MEETUP_COM_OAUTH_KEY)%'
    meetup_com_oauth_secret: '%env(MEETUP_COM_OAUTH_SECRET)%'

    found_meetups_storage_file: '%kernel.project_dir%/source/_data/generated/found_meetups.yml'
    topics_to_crawl:
        # 1st wave
#        - 'php'
#        - 'laravel'
#        - 'symfony'
#        - 'cakephp'
#        - 'php-framework'
        # 2nd wave
        - 'php-application-development'
        - 'symfony2'
        - 'codeigniter'
        - 'zend-framework'
        # skip these groups to get performance - they are probably all already imported
        # - 'drupal'
        # - 'wordpress'
        # - 'magento'
        # - 'prestashop'

    usa_states:
        al: 'Alabama'
        ak: 'Alaska'
        as: 'American Samoa'
        az: 'Arizona'
        ar: 'Arkansas'
        ca: 'California'
        co: 'Colorado'
        ct: 'Connecticut'
        de: 'Delaware'
        dc: 'District Of Columbia'
        fm: 'Federated States Of Micronesia'
        fl: 'Florida'
        ga: 'Georgia'
        gu: 'Guam'
        hi: 'Hawaii'
        id: 'Idaho'
        il: 'Illinois'
        in: 'Indiana'
        ia: 'Iowa'
        ks: 'Kansas'
        ky: 'Kentucky'
        la: 'Louisiana'
        me: 'Maine'
        mh: 'Marshall Islands'
        md: 'Maryland'
        ma: 'Massachusetts'
        mi: 'Michigan'
        mn: 'Minnesota'
        ms: 'Mississippi'
        mo: 'Missouri'
        mt: 'Montana'
        ne: 'Nebraska'
        nv: 'Nevada'
        nh: 'New Hampshire'
        nj: 'New Jersey'
        nm: 'New Mexico'
        ny: 'New York'
        nc: 'North Carolina'
        nd: 'North Dakota'
        mp: 'Northern Mariana Islands'
        oh: 'Ohio'
        ok: 'Oklahoma'
        or: 'Oregon'
        pw: 'Palau'
        pa: 'Pennsylvania'
        pr: 'Puerto Rico'
        ri: 'Rhode Island'
        sc: 'South Carolina'
        sd: 'South Dakota'
        tn: 'Tennessee'
        tx: 'Texas'
        ut: 'Utah'
        vt: 'Vermont'
        vi: 'Virgin Islands'
        va: 'Virginia'
        wa: 'Washington'
        wv: 'West Virginia'
        wi: 'Wisconsin'
        wy: 'Wyoming'

    # non-existing countries at meetup.com
    invalid_country_codes:
        - 'ax'
        - 'bl'
        - 'bv'
        - 'cc'
        - 'cx'
        - 'gg'
        - 'hm'
        - 'im'
        - 'io'
        - 'je'
        - 'mp'
        - 'ms'
        - 'nf'
        - 'pn'
        - 'pr'
        - 'kp'
        - 'gs'
        - 'sj'
        - 'pm'
        - 'ss'
        - 'st'
        - 'sx'
        - 'tc'
        - 'tl'
        - 'um'
        - 'vc'
        - 'vi'
        - 'bq'
