services:
    _defaults:
        autowire: true
        public: true

    Fop\MeetupCom\:
        resource: "../src"

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Strings\StringFormatConverter: ~
