services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Fop\StaticSiteDumper\:
        resource: "../src"

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
