services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Fop\MeetupCom\:
        resource: "../src"
        exclude:
            - "../src/ValueObject/*"

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Strings\StringFormatConverter: ~
