imports:
    - { resource: 'parameters.yaml' }

parameters:
    # complete for your Nomad trip - currently western europe
    top_left_corner:
        latitude: 50
        longitude: 1
    bottom_right_corner:
        latitude: 35
        longitude: 10
    start_date: 2018-11-01
    end_date: 2018-12-15

services:
    _defaults:
        autowire: true
        public: true

    Fop\:
        resource: '../src'
        exclude: '../src/{Entity,HttpKernel/FopKernel.php,Contract}'

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Http\BetterGuzzleClient: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
