imports:
    - { resource: 'parameters.yaml' }
    - { resource: '../packages/*/config/config.yaml' }
    - { resource: 'config.local.yaml', ignore_errors: true }

services:
    _defaults:
        autowire: true
        public: true

    Fop\:
        resource: '../src'
        exclude: '../src/{Entity,HttpKernel/FopKernel.php,Contract}'

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Http\BetterGuzzleClient: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
