imports:
    - { resource: 'parameters.yaml' }
    - { resource: '../packages/*/config/config.yaml' }
    - { resource: 'config.local.yaml', ignore_errors: true }

services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    Fop\:
        resource: '../src'
        exclude:
            - '../src/Entity/*'
            - '../src/HttpKernel/*'
            - '../src/Contract/*'

    Symplify\PackageBuilder\Yaml\ParameterMergingYamlLoader: ~
    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~

    GuzzleHttp\Client: ~
    Symplify\PackageBuilder\Http\BetterGuzzleClient: ~
