imports:
    - { resource: '_data/' }

# imported also by statie.yml - needs to be standalone
parameters:
    # how many days into the future the meetups should be imported
    max_forecast_days: 30

    groups_storage: '%kernel.project_dir%/config/_data/groups.yaml'
    meetups_storage: '%kernel.project_dir%/config/_data/meetups.yaml'

    website_url: 'https://friendsofphp.org'

    # its still public in the footer, so no need to hide it
    # setup & manage here: https://console.cloud.google.com/apis/credentials
    google_api_key:  'AIzaSyA6vhz7PGvf5rHjfnX6Ye6j6Gz2WVvIRvY'
