# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy

on:
    push:
        branches:
            - master
    schedule:
        # * is a special character in YAML so you have to quote this string
        # https://crontab.guru/every-12-hours
        - cron: '0 */12 * * *'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    persist-credentials: false

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress

            -
                name: Build
                run: |
                    # configure timezone: https://stackoverflow.com/a/27052708/1348344
                    export TZ=Europe/Prague
                    bin/console import --ansi
                    bin/console dump-static-site --ansi
                env:
                    MEETUP_COM_OAUTH_KEY: ${{ secrets.MEETUP_COM_OAUTH_KEY }}
                    MEETUP_COM_OAUTH_SECRET: ${{ secrets.MEETUP_COM_OAUTH_SECRET }}

            -
                name: Deploy
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output
