# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: composer install --no-progress

            -
                name: Build
                run: |
                    # configure timezone: https://stackoverflow.com/a/27052708/1348344
                    export TZ=Europe/Prague
                    bin/console import --ansi
                    bin/console dump-static-site --ansi
                env:
                    MEETUP_COM_OAUTH_KEY: ${{ secrets.MEETUP_COM_OAUTH_KEY }}
                    MEETUP_COM_OAUTH_SECRET: ${{ secrets.MEETUP_COM_OAUTH_SECRET }}
