name: Dead Groups

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    dead_groups:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: bin/console validate-dead-groups
