name: ECS

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer fix-cs

            # cannot commit into PRs, master only https://github.com/stefanzweifel/git-auto-commit-action/issues/25
    #            -
    #                name: Commit changed files
    #                uses: stefanzweifel/git-auto-commit-action@v2.5.0
    #                with:
    #                    commit_message: Apply ECS changes
    #                    branch: ${{ github.head_ref }}
    #                env:
    #                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
